apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: hostdev-device-plugin
  name: hostdev-device-plugin
  namespace: kube-system
  labels:
    name: hostdev-device-plugin-ds
spec:
  selector:
    matchLabels:
      name: hostdev-device-plugin-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: hostdev-device-plugin
    spec:
      nodeSelector:
        kubernetes.io/arch: arm
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      hostNetwork: true
      containers:
      - name: hostdev
        image: billimek/k8s-hostdev-plugin:0.1
        args: ["--devs", "/dev/mem:r"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
